apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-dashboard
  labels:
    app: weather-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-dashboard
  template:
    metadata:
      labels:
        app: weather-dashboard
    spec:
      containers:
      - name: weather-dashboard
        image: gcr.io/mishka-cme-project/weatherapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: WEATHER_API_KEY
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: gcp-key
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: gcp-key
        secret:
          secretName: weather-secrets
          items:
            - key: GOOGLE_APPLICATION_CREDENTIALS
              path: key.json
