name: Weather App CI/CD

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "mishka-cme-project"
  GKE_CLUSTER: "weather-gke-cluster"
  GKE_ZONE: "asia-south1"
  DEPLOYMENT_NAME: "weather-dashboard"
  REPOSITORY: "weatherapp"
  WORKLOAD_IDENTITY_PROVIDER: "projects/574573355783/locations/global/workloadIdentityPools/github-pool/providers/github"
  SERVICE_ACCOUNT: "github-deployer@mishka-cme-project.iam.gserviceaccount.com"

# -------------------------------
# 1️⃣ JOB: Build & Push Docker Image
# -------------------------------
jobs:
  build-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="gcr.io/${PROJECT_ID}/${REPOSITORY}:${GITHUB_SHA}"
          docker build -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"
  # -------------------------------
  # 2️⃣ JOB: Terraform Infra Apply
  # -------------------------------
  infra:
    name: Terraform Infra Apply
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

  
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_weather_api_key: ${{ secrets.WEATHER_API_KEY }}
          TF_VAR_service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

        run: terraform apply -auto-approve

  # -------------------------------
  # 3️⃣ JOB: Deploy to GKE
  # -------------------------------
  deploy:
    name: Deploy to GKE
    needs: infra
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy to GKE
        run: |
          IMAGE_TAG="gcr.io/${PROJECT_ID}/${REPOSITORY}:${GITHUB_SHA}"
          kubectl set image deployment/${DEPLOYMENT_NAME} weather-dashboard=$IMAGE_TAG
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
